//GET ALL COUNTRIES

export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ALL_COUNTRIES_EXITO = "GET_ALL_COUNTRIES_EXITO";
export const GET_ALL_COUNTRIES_ERROR = "GET_ALL_COUNTRIES_ERROR";

//GET ALL MATCHS

export const GET_ALL_MATCHS = "GET_ALL_MATCHS";
export const GET_ALL_MATCHS_EXITO = "GET_ALL_MATCHS_EXITO";
export const GET_ALL_MATCHS_ERROR = "GET_ALL_MATCHS_ERROR";

//SIGN UP USER

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_EXITO = "SIGN_UP_USER_EXITO";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";

//SIGN IN USER

export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_USER_EXITO = "SIGN_IN_USER_EXITO";
export const SIGN_IN_USER_ERROR = "SIGN_IN_USER_ERROR";

//SIGN OUT USER

export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGN_OUT_USER_EXITO = "SIGN_OUT_USER_EXITO";
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR";

//AGREGAR USUSARIO EN DB

export const ADD_USER_DB = "ADD_USER_DB";
export const ADD_USER_DB_EXITO = "ADD_USER_DB_EXITO";
export const ADD_USER_DB_ERROR = "ADD_USER_DB_ERROR";
