//GET ALL COUNTRIES

export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ALL_COUNTRIES_EXITO = "GET_ALL_COUNTRIES_EXITO";
export const GET_ALL_COUNTRIES_ERROR = "GET_ALL_COUNTRIES_ERROR";

//GET ALL MATCHS

export const GET_ALL_MATCHS = "GET_ALL_MATCHS";
export const GET_ALL_MATCHS_EXITO = "GET_ALL_MATCHS_EXITO";
export const GET_ALL_MATCHS_ERROR = "GET_ALL_MATCHS_ERROR";

//SIGN UP USER

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_EXITO = "SIGN_UP_USER_EXITO";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";
