//GET ALL COUNTRIES

export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ALL_COUNTRIES_EXITO = "GET_ALL_COUNTRIES_EXITO";
export const GET_ALL_COUNTRIES_ERROR = "GET_ALL_COUNTRIES_ERROR";

//GET ALL MATCHS

export const GET_ALL_MATCHS = "GET_ALL_MATCHS";
export const GET_ALL_MATCHS_EXITO = "GET_ALL_MATCHS_EXITO";
export const GET_ALL_MATCHS_ERROR = "GET_ALL_MATCHS_ERROR";

//GET FIXTURE PRODE

export const GET_FIXTURE_PRODE = "GET_FIXTURE_PRODE";
export const GET_FIXTURE_PRODE_EXITO = "GET_FIXTURE_PRODE_EXITO";
export const GET_FIXTURE_PRODE_ERROR = "GET_FIXTURE_PRODE_ERROR";

//GET PREVIUOS FIXTURE PRODE

export const GET_PREVIOUS_FIXTURE_PRODE = "GET_PREVIOUS_FIXTURE_PRODE";
export const GET_PREVIOUS_FIXTURE_PRODE_EXITO =
	"GET_PREVIOUS_FIXTURE_PRODE_EXITO";
export const GET_PREVIOUS_FIXTURE_PRODE_ERROR =
	"GET_PREVIOUS_FIXTURE_PRODE_ERROR";
//GET TEAMS

export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_EXITO = "GET_TEAMS_EXITO";
export const GET_TEAMS_ERROR = "GET_TEAMS_ERROR";

//GET CURRENT FIXTURE

export const GET_CURRENT_FIXTURE = "GET_CURRENT_FIXTURE";
export const GET_CURRENT_FIXTURE_EXITO = "GET_CURRENT_FIXTURE_EXITO";
export const GET_CURRENT_FIXTURE_ERROR = "GET_CURRENT_FIXTURE_ERROR";

//SIGN UP USER

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_EXITO = "SIGN_UP_USER_EXITO";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";

//SIGN IN USER

export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_USER_EXITO = "SIGN_IN_USER_EXITO";
export const SIGN_IN_USER_ERROR = "SIGN_IN_USER_ERROR";

//SIGN OUT USER

export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGN_OUT_USER_EXITO = "SIGN_OUT_USER_EXITO";
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR";

//AGREGAR USUSARIO EN DB

export const ADD_USER_DB = "ADD_USER_DB";
export const ADD_USER_DB_EXITO = "ADD_USER_DB_EXITO";
export const ADD_USER_DB_ERROR = "ADD_USER_DB_ERROR";

//GET USER INFO

export const GET_USER_DB = "GET_USER_DB";
export const GET_USER_DB_EXITO = "GET_USER_DB_EXITO";
export const GET_USER_DB_ERROR = "GET_USER_DB_ERROR";

//GET ALL USERS

export const GET_ALL_USERS_DB = "GET_ALL_USERS_DB";
export const GET_ALL_USERS_DB_EXITO = "GET_ALL_USERS_DB_EXITO";
export const GET_ALL_USERS_DB_ERROR = "GET_ALL_USERS_DB_ERROR";

//UPDATE USUSARIO EN DB

export const UPDATE_USER_DB = "UPDATE_USER_DB";
export const UPDATE_USER_DB_EXITO = "UPDATE_USER_DB_EXITO";
export const UPDATE_USER_DB_ERROR = "UPDATE_USER_DB_ERROR";

//UPDATE PRODE EN DB

export const UPDATE_USER_PRODE_DB = "UPDATE_USER_PRODE_DB";
export const UPDATE_USER_PRODE_DB_EXITO = "UPDATE_USER_PRODE_DB_EXITO";
export const UPDATE_USER_PRODE_DB_ERROR = "UPDATE_USER_PRODE_DB_ERROR";
